ersion: '3.8'

services:
  django-app:
    build: .
    container_name: protected-app
    volumes:
      - .:/app
      - /tmp:/tmp
      - /dev/bus/usb:/dev/bus/usb
    device_cgroup_rules:
      - 'c 189:* rmw'
    cap_add:
      - SYS_ADMIN
      - SYS_RAWIO
    ports:
      - "8000:8000"
    # volumes:
    #   - .:/app
    #   - /tmp:/tmp
    #   - type: bind
    #     source: /dev/bus/usb
    #     target: /dev/bus/usb
    #     bind:
    #       propagation: rshared
    # security_opt:
    #   - no-new-privileges  # Prevents the container from gaining additional privileges
    # privileged: true
    # https://stackoverflow.com/questions/24225647/docker-a-way-to-give-access-to-a-host-usb-or-serial-device/66427245#66427245
    # depends_on:
    #   - db
    # environment:
    #   - DEBUG=True
    #   - DB_NAME=your_db_name
    #   - DB_USER=your_db_user
    #   - DB_PASSWORD=your_db_password
    #   - DB_HOST=db
    # networks:
    #   - app-network

  # db:
  #   image: postgres:13
  #   environment:
  #     POSTGRES_DB: your_db_name
  #     POSTGRES_USER: your_db_user
  #     POSTGRES_PASSWORD: your_db_password
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   networks:
  #     - app-network


# volumes:
#   postgres_data:

# networks:
#   app-network:
