version: '3.8'

services:
  django-app:
    build: .
    # command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - /tmp:/tmp
    ports:
      - "8000:8000"
    # depends_on:
    #   - db
    # environment:
    #   - DEBUG=True
    #   - DB_NAME=your_db_name
    #   - DB_USER=your_db_user
    #   - DB_PASSWORD=your_db_password
    #   - DB_HOST=db
    # networks:
    #   - app-network

  # db:
  #   image: postgres:13
  #   environment:
  #     POSTGRES_DB: your_db_name
  #     POSTGRES_USER: your_db_user
  #     POSTGRES_PASSWORD: your_db_password
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   networks:
  #     - app-network


# volumes:
#   postgres_data:

# networks:
#   app-network: