services:
  protected-code:
    build: .
    container_name: protected-software
    volumes:
      - .:/app
      - /tmp:/tmp
      - /dev/bus/usb:/dev/bus/usb
      - /opt/Microcosm:/opt/Microcosm
    device_cgroup_rules:
      - 'c 189:* rmw'
    cap_add:
      - SYS_ADMIN
      - SYS_RAWIO
    ports:
      - "8000:8000"