# Generated by Django 5.1.1 on 2024-10-16 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='name',
            field=models.CharField(help_text='Name of sample', max_length=255),
        ),
    ]
